routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InquiryController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\SettingController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear_command', function () {
    Artisan::call('route:clear');
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('view:clear');
    // Artisan::call('package:discover --ansi');
    return back();
});



Route::prefix('/')->group(function(){

    Route::get('/', [FrontController::class,'index']);
    Route::get('contactus',[FrontController::class,'contactus'])->name('contactus');
    Route::get('about',[FrontController::class,'about'])->name('about');
    Route::get('services',[FrontController::class,'services'])->name('services');
    Route::view('portfolio','front.portfolio')->name('portfolio');
    Route::view('portfolio_details','front.portfolio_details')->name('portfolio_details');
    
    Route::post('inquiry',[InquiryController::class,'inquiry_front'])->name('inquiry_front');
});

Route::prefix('/admin')->group(function(){

    Route::get('/',function(){
        return redirect()->route((Auth::check()) ? 'home' : 'login');
    });

    Route::get('/login/google', [LoginController::class, 'redirectToGoogle'])->name('login.google');
    Route::get('/login/google/callback', [LoginController::class, 'handleGoogleCallback'])->name('login.google.callback');
    Route::get('/login/facebook/callback', [LoginController::class,'handleFacebookCallback'])->name('login.facebook');

    Auth::routes();

    Route::middleware(['auth'])->group(function () {
        Route::any('/lock', [HomeController::class, 'lock_screen'])->name('lock-screen');
        Route::middleware(['auto.lock'])->group(function () {
            Route::get('/home', [HomeController::class, 'index'])->name('home');
            Route::any('/profile', [HomeController::class, 'profile'])->name('admin.profile');
            Route::any('/contactus',[HomeController::class,'contactus'])->name('admin.contactus');
            Route::any('/aboutus',[HomeController::class,'aboutus'])->name('admin.aboutus');
            Route::any('/setting',[SettingController::class,'index'])->name('admin.setting');
            
            Route::get('/portfolio',[PortfolioController::class,'index'])->name('admin.portfolio');
            Route::post('/portfolio/update',[PortfolioController::class,'portfolio'])->name('admin.portfolio.update');
            

            Route::prefix('services')->name('admin.')->controller(ServiceController::class)->group(function(){
                Route::get('/','index')->name('services');
                Route::get('/add','add')->name('services.add');
                Route::post('/store','store')->name('services.store');
                Route::get('/edit/{id}','edit')->name('services.edit');
                Route::post('/update','update')->name('services.update');
                Route::post('/delete/{id}','delete')->name('services.delete');
            });

            Route::prefix('company')->name('admin.')->controller(CompanyController::class)->group(function(){
                Route::get('/','index')->name('company');
                Route::get('/add','add')->name('company.add');
                Route::post('/store','store')->name('company.store');
                Route::get('/edit/{id}','edit')->name('company.edit');
                Route::post('/update','update')->name('company.update');
                Route::post('/delete/{id}','delete')->name('company.delete');
            });

            Route::prefix('inquiry')->name('admin.')->controller(InquiryController::class)->group(function(){
                Route::get('/','index')->name('inquiry');
                Route::get('/add','add')->name('inquiry.add');
                Route::post('/store','store')->name('inquiry.store');
                Route::get('/edit/{id}','edit')->name('inquiry.edit');
                Route::post('/update','update')->name('inquiry.update');
                Route::post('/delete/{id}','delete')->name('inquiry.delete');
            });

            Route::prefix('invoice')->name('admin.')->controller(InvoiceController::class)->group(function(){
                Route::get('/','index')->name('invoice');
                Route::get('/add','add')->name('invoice.add');
                Route::post('/store','store')->name('invoice.store');
                Route::get('/edit/{id}','edit')->name('invoice.edit');
                Route::post('/update','update')->name('invoice.update');
                Route::post('/delete/{id}','delete')->name('invoice.delete');
                Route::get('/download_invoice/{id}','download_invoice')->name('invoice.download');
            });



        });
    });


});

resources/views/layouts/partials/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; {{ date('Y') }} <a href="#"> {{ config('app.name') }} </a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.1
    </div>
  </footer>

resources/views/layouts/partials/footerscript.blade.php
<!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>

<!-- jQuery -->
<script src="{{ asset('public/assets/plugins/jquery/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('public/assets/plugins/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('public/assets/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- ChartJS -->
<script src="{{ asset('public/assets/plugins/chart.js/Chart.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('public/assets/plugins/moment/moment.min.js') }}"></script>
<script src="{{ asset('public/assets/plugins/daterangepicker/daterangepicker.js') }}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('public/assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}"></script>
<!-- Summernote -->
<script src="{{ asset('public/assets/plugins/summernote/summernote-bs4.min.js') }}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('public/assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('public/assets/dist/js/adminlte.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('public/assets/dist/js/pages/dashboard.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('public/assets/dist/js/demo.js') }}"></script>

<script src="{{ asset('public/front/assets/js/jquery.validate.min.js') }}"></script>


<script src="{{ asset('public\assets\plugins\datatables\jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('public\assets\plugins\datatables-bs4\js\dataTables.bootstrap4.min.js') }}"></script>

<script src="{{ asset('public\assets\plugins\ekko-lightbox\ekko-lightbox.min.js') }}"></script>



<script src="{{ asset('public/assets/plugins/sweetalert2/sweetalert2.all.min.js') }}"></script>
<script src="https://cdn.ckeditor.com/4.22.1/full/ckeditor.js"></script>

resources/views/layouts/partials/header.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a class="nav-link" href="{{ route('logout') }}"
      onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
          {{ __('Logout') }}
      </a>

      <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
          @csrf
      </form>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{{ asset('public/assets/dist/img/user1-128x128.jpg') }}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{{ asset('public/assets/dist/img/user8-128x128.jpg') }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="{{ asset('public/assets/dist/img/user3-128x128.jpg') }}" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="{{ route('home') }}" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      @php
        $inquiryCount = \App\Models\Inquiry::whereDate('created_at',date('Y-m-d'))->count();
        $invoiceDueCount = \App\Models\Invoice::whereDate('due_date',date('Y-m-d'))->count();
        $notify = $inquiryCount + $invoiceDueCount;
      @endphp
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">{{ $notify }}</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-item dropdown-header">{{ $notify }} Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="{{ route('admin.inquiry') }}" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i>{{ $inquiryCount }} new inquiry
          <span class="float-right text-muted text-sm">Today</span>
        </a>
        <div class="dropdown-divider"></div>
        {{-- <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a> 
        <div class="dropdown-divider"></div>--}}
        <a href="{{ route('admin.invoice') }}" class="dropdown-item">
          <i class="fas fa-file mr-2"></i>{{ $invoiceDueCount }} invoice due
          <span class="float-right text-muted text-sm">Today</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="{{ route('home') }}" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>

    <!-- Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-user"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <a href="{{ route('admin.profile') }}" class="dropdown-item">
          <i class="fa-solid fa-user mr-2"></i> Profile
        </a>
        <div class="dropdown-divider"></div>
        <a href="javascript:void(0)" onclick="$('#logout-form').submit()" class="dropdown-item">
          <i class="fa-solid fa-right-from-bracket mr-2"></i> Logout
        </a>
        <form action="{{ route('logout') }}" id="logout-form" method="POST"></form>
      </div>
    </li>
    {{--  <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>  --}}
  </ul>
</nav>
<!-- /.navbar -->

resources/views/layouts/partials/headerscript.blade.php
<!-- Font Awesome -->
{{-- <link rel="stylesheet" href="{{ asset('public/assets/plugins/fontawesome-free/css/all.min.css') }}"> --}}
<link rel="stylesheet" href="{{ asset('public/assets/plugins/fontawesome-free/css/all-6.4.0.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bbootstrap 4 -->
<link rel="stylesheet" href="{{ asset('public/assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- iCheck -->
<link rel="stylesheet" href="{{ asset('public/assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
<!-- JQVMap -->
<link rel="stylesheet" href="{{ asset('public/assets/plugins/jqvmap/jqvmap.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('public/assets/dist/css/adminlte.min.css') }}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{{ asset('public/assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css') }}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('public/assets/plugins/daterangepicker/daterangepicker.css') }}">
<!-- summernote -->
<link rel="stylesheet" href="{{ asset('public/assets/plugins/summernote/summernote-bs4.css') }}">

<link rel="stylesheet" href="{{ asset('public\assets\plugins\datatables-bs4\css\dataTables.bootstrap4.min.css') }}">
<link rel="stylesheet" href="{{ asset('public\assets\plugins\ekko-lightbox\ekko-lightbox.css') }}">

<!-- Google Font: Source Sans Pro -->
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet"> 

resources/views/layouts/partials/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <img src="{{ (setting('logo')) ? url('storage/app/setting/'.setting('logo')) : asset('public/assets/dist/img/AdminLTELogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light d-table-cell">@yield('project_title')</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{ (auth()->user()->image) ? url('storage/app/profile/'.auth()->user()->image) : noimage(1) }}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="{{ route('admin.profile') }}" class="d-block">{{ auth()->user()->name }}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item">
          <a href="{{ route('home') }}" class="nav-link @if(Route::is('home')) active @endif">
            <i class="far fa-circle nav-icon"></i>
            <p>Dashboard</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.portfolio') }}" class="nav-link @if(Route::is('admin.portfolio')) active @endif">
            <i class="far fa-contact-book nav-icon"></i>
            <p>Portfolio</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.services') }}" class="nav-link @if(Route::is('admin.services')) active @endif">
            <i class="fa fa-archive nav-icon"></i>
            <p>Services</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.company') }}" class="nav-link @if(Route::is('admin.company')) active @endif">
            <i class="far fa-building nav-icon"></i>
            <p>Companies</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.inquiry') }}" class="nav-link @if(Route::is('admin.inquiry')) active @endif">
            <i class="nav-icon fa-solid fa-users"></i>
            <p>
              Inquiry
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.invoice') }}" class="nav-link @if(Route::is('admin.invoices')) active @endif">
            <i class="far fa-file nav-icon"></i>
            <p>Invoices</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.contactus') }}" class="nav-link @if(Route::is('admin.contactus')) active @endif">
            <i class="nav-icon fa-solid fa-users"></i>
            <p>
              Contact Us
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.aboutus') }}" class="nav-link @if(Route::is('admin.aboutus')) active @endif">
            <i class="nav-icon fa-solid fa-address-book"></i>
            <p>
              About Us
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.setting') }}" class="nav-link @if(Route::is('admin.setting')) active @endif">
            <i class="nav-icon fa-solid fa-cog"></i>
            <p>
              Settings
            </p>
          </a>
        </li>


        <li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-copy"></i>
            <p>
              Layout Options
              <i class="fas fa-angle-left right"></i>
              <span class="badge badge-info right">6</span>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Top Navigation</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="far fa-circle nav-icon"></i>
                <p>Collapsed Sidebar</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-header">EXAMPLES</li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon far fa-calendar-alt"></i>
            <p>
              Calendar
              <span class="badge badge-info right">2</span>
            </p>
          </a>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>